services:
  backend:
    container_name: capstone-rma-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/db.json:/db.json
    networks:
      - rma-network
    mem_limit: 128m 
    cpus: 0.25 


  frontend:
    container_name: capstone-rma-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - rma-network
    mem_limit: 256m 
    cpus: 0.5 

networks:
  rma-network:
    driver: bridge